export const EXAM_LIST_REQUEST = "EXAM_LIST_REQUEST";
export const EXAM_LIST_SUCCESS = "EXAM_LIST_SUCCESS";
export const EXAM_LIST_FAIL = "EXAM_LIST_FAIL";

export const EXAM_SCHEDULE_REQUEST = "EXAM_SCHEDULE_REQUEST";
export const EXAM_SCHEDULE_SUCCESS = "EXAM_SCHEDULE_SUCCESS";
export const EXAM_SCHEDULE_FAIL = "EXAM_SCHEDULE_FAIL";
